# Generated by Django 5.0.4 on 2025-07-11 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("tienda", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logadmin",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="pedido",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venta",
                to="tienda.pedido",
            ),
        ),
    ]
