services:
  - type: web
    name: yecy-cosmetic
    env: python
    rootDir: backend
    buildCommand: >
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput && \
      python manage.py migrate
    startCommand: gunicorn yecy_cosmetic.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase: true
      - key: SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.render.com,localhost"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.render.com"
    pythonVersion: 3.11
    databases:
      - name: yecy-cosmetic-db
        type: postgresql
        size: 100MB
