# Generated by Django 5.0.4 on 2025-07-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0003_estadoventa_pedido_activo_pedido_creado_por_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagenproducto",
            options={"ordering": ["orden", "id"]},
        ),
        migrations.AddField(
            model_name="imagenproducto",
            name="es_principal",
            field=models.BooleanField(
                default=False, help_text="Indica si es la imagen principal del producto"
            ),
        ),
        migrations.AddField(
            model_name="imagenproducto",
            name="url_imagen",
            field=models.URLField(
                blank=True, help_text="URL de imagen externa", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="imagenproducto",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="productos/imagenes/"
            ),
        ),
    ]
