# Generated by Django 5.0.4 on 2025-07-17 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0004_alter_imagenproducto_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="activa",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="activo",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="destacado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fecha_creacion",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="activa",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
